### ISSUE TITLE
error: unable to read askpass response from 'rpostback-askpass’ " while using a MAC

### ISSUE THREAD

**Issue by alanarnholt** [STT2810-SP15/DiscussionSTT2810#2]
If you are encountering an message to the effect: "error: unable to read askpass response from 'rpostback-askpass’ " while using a MAC,  the problem will most likely disappear if you use the credential helper.

To find out if the credential helper is already installed. In the shell, enter `git credential-osxkeychain`. You should see something like this: `Usage: git credential-osxkeychain <get|store|erase>`. 

Once you’ve confirmed you have the credential helper, enter 
`git config --global credential.helper osxkeychain`.

Further directions are available on GitHub https://help.github.com/articles/caching-your-github-password-in-git/

This fixed the problem on one machine this afternoon.  I would like to get feedback if the proposed solution works for others that are having this problem...

**Comment by dorvilled** [comment]
My mac is still getting the some error and when I enter the "git credential-osxkeychain" in rstudio I get "Error: unexpected symbol in "git credential"" but when I enter it in terminal I get the Usage: git credential-osxkeychain <get|store|erase>. Not sure what to do.

**Comment by alanarnholt** [comment]
You need to enter 

`git config --global credential.helper osxkeychain`

in the terminal

**Comment by dorvilled** [comment]
I do that and I still get the same error

**Comment by alanarnholt** [comment]
1. Please copy everything you are typing in the terminal and the subsequent  error message below...

2. What is your output after typing

`git config --list`

**Comment by brittanyrogers** [comment]
I tried this and mine says

credential.helper=osxkeychain

still getting the same errors.

**Comment by alanarnholt** [comment]
For all running into this issue you need to make sure 
1. You have told Git who you are (user.name, and email)
2. Clone a public repo.  Then push a public repo so that you have to type your username and password.
3. After step 2 your credentials should be established.

**Comment by alanarnholt** [comment]
If you are still running into problems after following the above three steps, from the terminal (recall this for MAC users) ... Fork a private repo...change something in the forked repo (a line in the README say) then from the terminal enter:

`git add . `
`git commit -m"first commit or something"`
`git push`

You will need to enter your username and password at the appropriate prompt.
If your 'push` is successful, your credentials will be stored and you should be good to go using RStudio to push and pull now.
