### ISSUE TITLE
Literature Review in the Introduction

### ISSUE THREAD

**Issue by huertact** [STT2810-SP15/DiscussionSTT2810#4]
The PDS textbook states that we should include our Literature Review in the 'introduction' section of the research proposal. Should I physically attach the file, or just include what I talked about from my lit review?

**Comment by alanarnholt** [comment]
You will have file quite possibly named ResearchProposal.html that you will submit to crowdgrader.  The submitted *.html file will be created from a *.Rmd file in a manner similar to the Citation assignment.  I would create a file quite possibly named ResearchPropsal.Rmd ... in said file you will have your literature review which may be similar to your first assignment or you may want to tweak it some.  The format in the book is recreated in the https://github.com/STT2810-SP15/STT2810ClassRepoSP15/tree/master/ResearchProposal folder.  The example on GitHub should be a great template for your proposal.

To not attach the file...include or modify from your previous assignment in the appropriate section.
